# Generated by Django 4.2.2 on 2023-09-06 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_accounts',
            new_name='user_account',
        ),
    ]
