# Generated by Django 4.2.2 on 2023-09-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym1', '0003_user_details_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='photo',
            field=models.CharField(max_length=300),
        ),
    ]
