# Generated by Django 4.0.4 on 2023-09-09 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym1', '0004_alter_user_details_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='trainer_account',
        ),
    ]
