# Generated by Django 4.2.2 on 2023-09-26 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym1', '0005_delete_trainer_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainername', models.CharField(max_length=30)),
                ('typeofsession', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('photo', models.CharField(max_length=30)),
                ('available_slot', models.CharField(max_length=30)),
                ('catagory', models.CharField(max_length=30)),
                ('starting_date', models.DateField(max_length=30)),
                ('status', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='trainer_details',
            name='photo',
            field=models.CharField(max_length=300),
        ),
        migrations.CreateModel(
            name='usergymdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainername', models.CharField(max_length=30)),
                ('packgname', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('joining_date', models.DateField(max_length=30)),
                ('start_date', models.DateField(max_length=30)),
                ('photo', models.CharField(max_length=30)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('selfinto', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym1.user_details')),
            ],
        ),
    ]
