# Generated by Django 4.2.2 on 2023-09-26 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym1', '0006_packages_alter_trainer_details_photo_usergymdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usergymdata',
            new_name='usergym_data',
        ),
    ]
