# Generated by Django 4.2.2 on 2023-09-29 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym1', '0008_rename_usergym_data_user_gymdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_gymdata',
            new_name='user_gym_data',
        ),
    ]
