# Generated by Django 4.2.2 on 2023-09-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym1', '0009_rename_user_gymdata_user_gym_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_gym_data',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
