# Generated by Django 4.2.2 on 2023-09-29 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym1', '0010_alter_user_gym_data_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packages',
            old_name='catagory',
            new_name='category',
        ),
    ]
