# Generated by Django 4.0.4 on 2023-10-26 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym1', '0012_rename_selfinto_user_gym_data_selfintro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_gym_data',
            name='selfintro',
            field=models.CharField(max_length=500),
        ),
    ]
